# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

   config.vm.define "server" do |webserver|

  webserver.vm.box = "ubuntu/trusty64"
  webserver.vm.box_check_update = false

  webserver.vm.network "forwarded_port", guest: 8080, host: 8082

  webserver.vm.network "private_network", type: "static", ip: "192.168.2.10"

  webserver.vm.synced_folder "./tomcatwebapps", "/opt/tomcat/webapps"

  
  
   webserver.vm.provider "virtualbox" do |vb|
  vb.gui = false
  vb.name = "webserver-tomcat"
  vb.memory = "1024" 
   end
  end

  config.vm.define "preprodserver" do |preprodwebserver|

   preprodwebserver.vm.box = "bento/ubuntu-22.04"
   preprodwebserver.vm.box_check_update = false
 
   preprodwebserver.vm.network "forwarded_port", guest: 8080, host: 8083
 
   preprodwebserver.vm.network "private_network", type: "static", ip: "192.168.2.11"
 
   preprodwebserver.vm.synced_folder "./tomcatwebapps", "/opt/tomcat/webapps"
 
   
   
   preprodwebserver.vm.provider "virtualbox" do |vb|
   vb.gui = false
   vb.name = "preprodwebserver-tomcat"
   vb.memory = "1024" 
    end
   end

  end
